In [51]:
import pandas as pd, numpy as np
from copy import deepcopy
pred = pd.read_csv('/Users/yunfanz/TestSet1Predictions.csv')

In [52]:
cols = pred.columns[1:]
pred.head(n=5)
print(cols, len(cols))


Index(['16PSK', '2FSK_5KHz', '2FSK_75KHz', '8PSK', 'AM_DSB', 'AM_SSB',
       'APSK16_c34', 'APSK32_c34', 'BPSK', 'CPFSK_5KHz', 'CPFSK_75KHz',
       'FM_NB', 'FM_WB', 'GFSK_5KHz', 'GFSK_75KHz', 'GMSK', 'MSK', 'NOISE',
       'OQPSK', 'PI4QPSK', 'QAM16', 'QAM32', 'QAM64', 'QPSK'],
      dtype='object') 24


In [4]:
# pred['PI4QPSK'] = 1.e-15
# pred['FM_NB'] = 1.e-15  set this next time, skipping to see effect
# pred['FM_WB'] = 1.e-15

In [53]:
confusion = ['QAM32','QAM64','QAM16','APSK16_c34','APSK32_c34']
con_arr = np.sort([list(cols).index(col) for col in confusion])
con_arr

array([ 6,  7, 20, 21, 22])

In [70]:
pred_arr = np.array(pred[cols])
print(pred_arr.shape)
pred_arr[1]

(100000, 24)


array([ 0.00297351,  0.00295099,  0.00295099,  0.00295824,  0.00295099,
        0.00295099,  0.02615513,  0.78644389,  0.00295099,  0.00295099,
        0.00295099,  0.00295099,  0.00295099,  0.00295099,  0.00295099,
        0.00295099,  0.00295099,  0.00295099,  0.00295099,  0.00295101,
        0.0161348 ,  0.03114858,  0.08401906,  0.002951  ])

In [71]:
EPS = 0.025
for j, row in enumerate(pred_arr):
    if np.argmax(row) in con_arr:
        group = deepcopy(row[con_arr])
        #print(group)
        for i in range(con_arr.size):
            group[i] = 0.75*group[i] + 0.05*np.sum(row[con_arr]) 
        #print(group)
        
        #print(pred_arr[j][con_arr])
        pred_arr[j][con_arr] = group
        #print(pred_arr[j][con_arr])
        #break

In [82]:
new_pred = pd.DataFrame(pred_arr, columns=cols)
new_pred['Index'] = pred['Index']

In [83]:
new_pred.set_index('Index', inplace=True)
new_pred.head(n=5)

16PSK  2FSK_5KHz  2FSK_75KHz      8PSK    AM_DSB    AM_SSB  \
Index                                                                  
1      0.000893   0.000893    0.000893  0.000893  0.000893  0.979457   
2      0.002974   0.002951    0.002951  0.002958  0.002951  0.002951   
3      0.000900   0.000900    0.000900  0.000900  0.000900  0.000900   
4      0.000893   0.000893    0.979457  0.000893  0.000893  0.000893   
5      0.000478   0.001545    0.000478  0.000478  0.482734  0.485513   

       APSK16_c34  APSK32_c34      BPSK  CPFSK_5KHz    ...     GFSK_75KHz  \
Index                                                  ...                  
1        0.000893    0.000893  0.000893    0.000893    ...       0.000893   
2        0.066811    0.637028  0.002951    0.002951    ...       0.002951   
3        0.049823    0.783603  0.000900    0.000900    ...       0.000900   
4        0.000893    0.000893  0.000893    0.000893    ...       0.000893   
5        0.000478    0.000478  0.000478    0.005247    ...       0.000478   

           GMSK       MSK     NOISE     OQPSK   PI4QPSK     QAM16     QAM32  \
Index                                                                         
1      0.000893  0.000893  0.000893  0.000893  0.000893  0.000893  0.000893   
2      0.002951  0.002951  0.002951  0.002951  0.002951  0.059296  0.070557   
3      0.000900  0.000900  0.000900  0.000900  0.000900  0.049827  0.049827   
4      0.000893  0.000893  0.000893  0.000893  0.000893  0.000893  0.000893   
5      0.000478  0.000478  0.000478  0.000478  0.000478  0.000478  0.000478   

          QAM64      QPSK  
Index                      
1      0.000893  0.000893  
2      0.110209  0.002951  
3      0.049827  0.000900  
4      0.000893  0.000893  
5      0.000478  0.000478  

[5 rows x 24 columns]

In [85]:
new_pred.to_csv('./test.csv',float_format='%.8f')

In [86]:
pred_mods = np.argmax(pred_arr, axis=1)

In [87]:
pred_mods.shape

(100000,)

In [96]:
np.array([p in con_arr for p in pred_mods]).nonzero()[0][0]

1

In [91]:
con_arr

array([ 6,  7, 20, 21, 22])